### ISSUE TITLE
Move our global filter to above the call to shortcode_atts so we can switch away from extract

### ISSUE THREAD

**Issue by BraadMartin** [MIGHTYminnow/mm-components#18]
Currently we are passing $atts to our global filter on all components, but we're doing this after we call shortcode_atts, which is causing $atts to not be the same $atts as we need it to be. We should move our global filter to be first inside our shortcode functions, then call shortcode_atts, then build our CSS classes after that.

**Comment by MickeyKay** [comment]
This can be fixed across the board by moving these two line:

```
// Generate base component class.
$mm_classes = str_replace( '_', '-', $tag );
$mm_classes = apply_filters( VC_SHORTCODE_CUSTOM_CSS_FILTER_TAG, $mm_classes, $tag, $atts );
```

Above the call to `shortcode_atts()`
